name: syncToGitee
on: 
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: tuya/TuyaOpen-T5AI@master
      with:
        target-url: 'https://gitee.com/tuya-open/TuyaOpen-T5AI.git'
        target-username: 'flyingcys'
        target-token: ${{ secrets.GITEE_TOKEN }}
